In [17]:
import numpy as np

In [18]:
# create one dimmensional array
my_1d_array = np.array([1, 2, 3])
my_1d_array

array([1, 2, 3])

In [19]:
# inspect shape of one dimensional array
my_1d_array.shape # 1 row, 3 columns

(3,)

In [20]:
# access elements in a one dimmensional array
print(my_1d_array[0])
print(my_1d_array[-1])
print(my_1d_array[0:2])

1
3
[1 2]


In [21]:
# create two dimensional array
my_2d_array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
my_2d_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [22]:
# inspect shape of two dimensional array
my_2d_array.shape # 2 rows, 5 columns

(2, 5)

In [23]:
# access elements in a two dimmensional array
print(my_2d_array[0]) # row at index zero
print(my_2d_array[1]) # row at index 1
print(my_2d_array[0, 1]) # row at index 0, column at index 1
print(my_2d_array[0][1]) # same as above with different syntax
print(my_2d_array[0:2, 1:3]) # slicing 


[1 2 3 4 5]
[ 6  7  8  9 10]
2
2
[[2 3]
 [7 8]]


In [24]:
# create array with 0 (useful to start with a base array of a certain shape)
# can also use np.ones to fill an array with 1
print(np.zeros(3))
print('\n')

print(np.zeros((3, 3)))
print('\n')

print(np.zeros((3, 3, 3)))

[0. 0. 0.]


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [25]:
# create array and fill with a specified value
np.full((3, 3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [26]:
# create array and fill with a specified range (start, stop, step)
print(np.arange(10))
print(np.arange(2, 10))
print(np.arange(2, 10, 2))

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 4 6 8]


In [27]:
# create array with evenly spaced values that will form a straight line (start, stop, step)
np.linspace(1, 5, 20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [28]:
# rounding all values in an array
float_array = np.linspace(1, 5, 20)
np.round(float_array, 2)

array([1.  , 1.21, 1.42, 1.63, 1.84, 2.05, 2.26, 2.47, 2.68, 2.89, 3.11,
       3.32, 3.53, 3.74, 3.95, 4.16, 4.37, 4.58, 4.79, 5.  ])

In [29]:
# create array with random numbers (rows, columns)
print(np.random.rand(5)) # one dimensional array with 5 values
print('\n')

print(np.random.rand(5, 2)) # two dimensional array with 5 rows and 2 columns

[0.93368091 0.5972166  0.95963574 0.7894635  0.68952737]


[[0.73205385 0.05755157]
 [0.91373957 0.39245089]
 [0.09207749 0.29187368]
 [0.24303343 0.74949354]
 [0.12628954 0.58942453]]


In [30]:
# create array with random integers (start, stop, count)
print(np.random.randint(20, 80, 100)) # one dimensional array
print('\n')

print(np.random.randint(20, 80, (10, 10))) # specify desired shape in paranthesis

[75 20 62 57 74 62 49 39 77 21 64 25 29 22 67 56 22 74 48 60 77 71 32 49
 23 36 50 23 23 65 71 65 29 60 75 20 32 67 27 22 39 48 21 54 79 54 70 59
 50 79 44 61 34 76 68 26 48 41 28 57 35 66 41 47 31 65 48 42 50 46 68 37
 42 23 69 60 26 56 54 43 41 40 68 77 27 36 47 35 20 22 77 61 77 54 25 32
 26 31 64 37]


[[65 76 73 44 39 33 44 32 44 24]
 [59 67 68 23 29 60 57 31 40 57]
 [24 22 65 62 46 23 33 51 27 66]
 [51 57 34 72 43 20 53 38 52 25]
 [26 24 63 75 68 71 37 30 68 27]
 [40 22 50 53 52 31 22 43 59 22]
 [61 27 58 35 37 61 54 73 43 61]
 [43 72 23 45 73 46 23 69 32 73]
 [71 54 46 72 24 66 38 36 24 27]
 [30 31 44 42 32 59 60 32 63 25]]


In [31]:
# reshaping an array
rand_1d_array = np.random.randint(20, 80, 100)
rand_2d_array = rand_1d_array.reshape(10, 10) # specify desired shape in paranthesis
rand_2d_array

array([[41, 45, 35, 25, 73, 41, 30, 47, 26, 27],
       [20, 40, 22, 50, 43, 51, 67, 76, 34, 79],
       [45, 45, 39, 71, 70, 66, 71, 64, 69, 67],
       [33, 36, 72, 53, 79, 70, 37, 59, 47, 42],
       [43, 27, 25, 69, 28, 72, 22, 53, 44, 25],
       [56, 35, 65, 64, 33, 32, 67, 24, 41, 36],
       [69, 60, 26, 48, 66, 30, 68, 48, 39, 62],
       [32, 36, 65, 65, 58, 24, 32, 37, 66, 73],
       [36, 44, 60, 56, 61, 64, 54, 22, 26, 27],
       [22, 40, 50, 21, 36, 64, 58, 49, 60, 69]])