In [2]:
import numpy as np

In [4]:
# create array and fill with zeros
my_1d_array = np.zeros(10)
my_1d_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
# changing single value in a one dimensional array
my_1d_array[0] = 1
my_1d_array

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
# changing multiple values in a one dimensional array
my_1d_array[1:5] = 1
my_1d_array

array([1., 1., 1., 1., 1., 0., 0., 0., 0., 0.])

In [17]:
# searching for values in an array
print(f"One Dimension: {np.where(my_1d_array == 1)}") # returns index locations were condition is True

my_2d_array = np.array([[1, 5, 9], [8, 5, 5]])
print(f"Two Dimension: {np.where(my_2d_array == 5)}")

One Dimension: (array([0, 1, 2, 3, 4], dtype=int64),)
Two Dimension: (array([0, 1, 1], dtype=int64), array([1, 1, 2], dtype=int64))


In [20]:
# additional search operations
print(f"< 5: {np.where(my_2d_array == 5)}")
print(f">= 5: {np.where(my_2d_array >= 5)}")
print(f"!= 5: {np.where(my_2d_array != 5)}")

< 5: (array([0, 1, 1], dtype=int64), array([1, 1, 2], dtype=int64))
>= 5: (array([0, 0, 1, 1, 1], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))
!= 5: (array([0, 0, 1], dtype=int64), array([0, 2, 0], dtype=int64))


In [22]:
# using a decalred variable that find values
index = np.where(my_2d_array > 5)
print(my_2d_array[index])

[9 8]


In [29]:
# check if all values meet a criteria
print(my_1d_array)
print(np.all(my_1d_array))
print(np.all(my_1d_array) >= 0)

[1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
False
True


In [30]:
# check if any values meet a criteria
print(my_1d_array)
print(np.any(my_1d_array))
print(np.any(my_1d_array) < 0)

[1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
True
False


In [47]:
# stacking values (arrays must have same shape)
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(f"a = {a}")
print(f"b = {b}")
print('\n')

v = np.vstack((a, b))
print(v)
print('\n')

v = np.vstack((a, b, a, b))
print(v)
print('\n')

h = np.hstack((a, b))
print(h)

h = np.hstack((a, b, a, b))
print(h)

a = [[1 2]
 [3 4]]
b = [[5 6]
 [7 8]]


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [1 2]
 [3 4]
 [5 6]
 [7 8]]


[[1 2 5 6]
 [3 4 7 8]]
[[1 2 5 6 1 2 5 6]
 [3 4 7 8 3 4 7 8]]


In [49]:
# flatten a two dimensional array into one dimension
print(my_2d_array)
my_2d_array.flatten()

[[1 5 9]
 [8 5 5]]


array([1, 5, 9, 8, 5, 5])