In [1]:
import numpy as np

In [3]:
# create one dimmensional array
my_1d_array = np.array([1, 2, 3])
my_1d_array

array([1, 2, 3])

In [9]:
# inspect shape of one dimensional array
my_1d_array.shape # 1 row, 3 columns

(3,)

In [6]:
# access elements in a one dimmensional array
print(my_1d_array[0])
print(my_1d_array[-1])
print(my_1d_array[0:2])

1
3
[1 2]


In [7]:
# create two dimensional array
my_2d_array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
my_2d_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
# inspect shape of two dimensional array
my_2d_array.shape # 2 rows, 5 columns

(2, 5)

In [15]:
# access elements in a two dimmensional array
print(my_2d_array[0]) # row at index zero
print(my_2d_array[1]) # row at index 1
print(my_2d_array[0, 1]) # row at index 0, column at index 1
print(my_2d_array[0][1]) # same as above with different syntax
print(my_2d_array[0:2, 1:3]) # slicing 


[1 2 3 4 5]
[ 6  7  8  9 10]
2
2
[[2 3]
 [7 8]]


In [28]:
# create array with 0 (useful to start with a base array of a certain shape)
# can also use np.ones to fill an array with 1
print(np.zeros(3))
print('\n')
print(np.zeros((3, 3)))
print('\n')
print(np.zeros((3, 3, 3)))

[0. 0. 0.]


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [30]:
# create array and fill with a specified value
np.full((3, 3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [32]:
# create array and fill with a specified range (start, stop, step)
print(np.arange(10))
print(np.arange(2, 10))
print(np.arange(2, 10, 2))

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 4 6 8]


In [34]:
# create array with evenly spaced values that will form a straight line (start, stop, step)
np.linspace(1, 5, 20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [37]:
# rounding all values in an array
float_array = np.linspace(1, 5, 20)
np.round(float_array, 2)

array([1.  , 1.21, 1.42, 1.63, 1.84, 2.05, 2.26, 2.47, 2.68, 2.89, 3.11,
       3.32, 3.53, 3.74, 3.95, 4.16, 4.37, 4.58, 4.79, 5.  ])

In [43]:
# create array with random numbers (rows, columns)
print(np.random.rand(5)) # one dimensional array with 5 values
print('\n')
print(np.random.rand(5, 2)) # two dimensional array with 5 rows and 2 columns

[0.15364422 0.36842217 0.11801474 0.49743742 0.48447978]


[[0.54112546 0.91912689]
 [0.52605475 0.19612239]
 [0.77273216 0.92250851]
 [0.11838072 0.05715875]
 [0.06408965 0.59774652]]


In [48]:
# create array with random integers (start, stop, count)
print(np.random.randint(20, 80, 100)) # one dimensional array
print('\n')
print(np.random.randint(20, 80, (10, 10))) # specify desired shape in paranthesis

[30 28 48 33 43 33 63 31 50 73 21 37 52 54 36 74 24 68 54 29 75 25 46 29
 25 51 40 68 41 35 61 67 42 70 34 74 55 63 27 39 58 79 38 41 26 56 64 77
 23 55 34 57 77 51 68 76 77 78 43 58 61 30 73 46 24 58 21 66 25 41 32 40
 28 45 54 42 23 29 34 49 45 58 45 64 44 62 40 56 42 45 62 26 73 78 74 26
 76 63 59 34]


[[54 53 37 38 77 42 42 76 35 56]
 [27 21 21 24 53 51 59 48 72 23]
 [42 72 74 72 46 67 36 53 43 76]
 [44 52 47 34 55 57 41 60 77 26]
 [67 44 30 58 59 29 58 55 76 47]
 [59 77 64 75 64 55 64 27 59 32]
 [71 21 20 22 20 56 50 39 49 62]
 [53 23 53 53 58 62 42 20 23 59]
 [62 54 74 73 47 54 55 33 22 25]
 [65 47 54 66 55 62 37 52 79 22]]


In [49]:
# reshaping an array
rand_1d_array = np.random.randint(20, 80, 100)
rand_2d_array = rand_1d_array.reshape(10, 10) # specify desired shape in paranthesis
rand_2d_array

array([[35, 50, 28, 53, 44, 36, 45, 25, 51, 37],
       [29, 20, 76, 24, 59, 57, 66, 43, 79, 64],
       [31, 63, 23, 68, 58, 71, 49, 44, 39, 77],
       [64, 44, 35, 58, 31, 71, 75, 59, 24, 53],
       [41, 53, 52, 55, 74, 67, 26, 21, 68, 79],
       [51, 59, 33, 46, 32, 35, 25, 78, 33, 66],
       [58, 65, 53, 60, 42, 33, 54, 53, 23, 54],
       [78, 74, 44, 55, 37, 46, 77, 31, 46, 34],
       [68, 67, 64, 22, 38, 20, 26, 64, 45, 52],
       [79, 74, 71, 56, 30, 27, 36, 42, 78, 32]])