In [35]:
import numpy as np

In [36]:
# create one dimensional array (start, stop, count)
my_1d_array = np.random.randint(2, 8, 16)
my_1d_array

array([2, 2, 4, 4, 5, 5, 4, 5, 6, 2, 4, 4, 4, 6, 3, 4])

In [37]:
# find max, min, mean, sum, and st dev values on one dimensional array
print(f"Max: {my_1d_array.max()}")
print(f"Min: {my_1d_array.min()}")
print(f"Mean: {my_1d_array.mean()}")
print(f"Sum: {my_1d_array.sum()}")
print(f"St Dev: {my_1d_array.std()}")

Max: 6
Min: 2
Mean: 4.0
Sum: 64
St Dev: 1.224744871391589


In [38]:
# create two dimensional array with reshape
my_2d_array = my_1d_array.reshape(4, 4)
my_2d_array

array([[2, 2, 4, 4],
       [5, 5, 4, 5],
       [6, 2, 4, 4],
       [4, 6, 3, 4]])

In [39]:
# find mean and st dev values on two dimensional arrays (same applies for other functions)
print(f"Mean Columns: {my_2d_array.mean(axis = 0)}") # max per column
print(f"Mean Rows: {my_2d_array.mean(axis = 1)}") # max per row
print('\n')

print(f"St Dev Columns: {my_2d_array.std(axis = 0)}") # max per column
print(f"St Dev Rows: {my_2d_array.std(axis = 1)}") # max per row

# to find the index positions of the max or min statitic, use arg max or arg min

Mean Columns: [4.25 3.75 3.75 4.25]
Mean Rows: [3.   4.75 4.   4.25]


St Dev Columns: [1.47901995 1.78535711 0.4330127  0.4330127 ]
St Dev Rows: [1.         0.4330127  1.41421356 1.08972474]


In [40]:
# sort array (not in place)
np.sort(my_1d_array)

array([2, 2, 2, 3, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 6, 6])

In [41]:
# mathematical operations
a = np.array([1, 2, 3, 4, 5])
a + 10 # same syntax for -, *, /, **

array([11, 12, 13, 14, 15])

In [42]:
# mathematical operations on two arrays (must have same shapes)
b = np.array([3, 7, 1, 2, 6])
a + b # same syntax for -, *, /, **

array([ 4,  9,  4,  6, 11])

In [43]:
# more mathematical operations
c = np.array([-2, -1, 0, 1, 2])
print(np.square(c))
print('\n')

print(np.sqrt(c))
print('\n')

print(np.sign(c))

[4 1 0 1 4]


[       nan        nan 0.         1.         1.41421356]


[-1 -1  0  1  1]


C:\Users\nick.reyes\AppData\Local\Temp\ipykernel_8928\545809106.py:6: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(c))


In [45]:
# trigonemtric operations
print(np.sin(c))
print('\n')

print(np.cos(c))
print('\n')

print(np.tan(c))

[-0.90929743 -0.84147098  0.          0.84147098  0.90929743]


[-0.41614684  0.54030231  1.          0.54030231 -0.41614684]


[ 2.18503986 -1.55740772  0.          1.55740772 -2.18503986]


In [47]:
# calculating dot product
d = np.array([1, 2, 3])
e = np.array([4, 5, 6])
np.dot(a, b)

58